name: hrf_vendors
description: A new Flutter application.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  provider: ^6.0.1
  connectivity: ^3.0.6
  dio: ^4.0.0-prev2
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  image_picker: ^0.8.0+4
  flutter_switch: ^0.3.0
  fl_chart: ^0.40.0
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_rating_bar: ^4.0.0
  flutter_typeahead: ^3.2.1
  autocomplete_textfield: ^1.7.3
  dotted_border: ^2.0.0+1
  path_provider: ^2.0.1
  flutter_html: ^2.0.0-nullsafety.0
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.jpg"


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/font/montserrat/Montserrat-Regular.otf
        - asset: assets/font/montserrat/Montserrat-Italic.otf
        - asset: assets/font/montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/font/montserrat/Montserrat-Bold.otf
          weight: 700
    